[package]
name = "bodeplot"
version = "1.0.0"
authors = ["Emil Loer <emil@koffietijd.net>"]
edition = "2018"
license = "GPL3"

[dependencies.kernel]
path = ".."

[dependencies]
clap = "3.0.0-beta.2"
num-complex = "0.3.1"
textplots = "0.5.4"
